GDS_App1: 
  provider: GoogleCloud
  host: https://storage.cloud.google.com/gds-workload/GCP1.png
  type: workload
  
GDS_app2: 
  provider: GoogleCloud
  host: https://storage.cloud.google.com/gds-workload/GCP2.png
  type: workload
